### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Sailorvp/prj-rev-bwfs-dasmoto#6]
https://github.com/Sailorvp/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%E2%80%98s%20Art/Resources/CSS/style.css#L15-L31

There is a bit of repetition going on in your CSS rules.

When you have some styles that need to get applied to several elements, write them in a single rule with a more general selector. 

```css
* {
  font-family: Helvetica;
}

.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes {
  background-color: mediumspringgreen;
}
```
